export type LessonExample = { title: string; description: string; code: string }
export type Lesson = { id:string; title:string; eyebrow:string; description:string; code:string; download?: 'basic'|'styled'|'table'|'chart'; downloadLabel?: string; note?:string; examples?: LessonExample[] }
export const lessons: Lesson[] = [
 {id:'welcome',title:'Welcome',eyebrow:'Start here',description:'A practical, browser-first ExcelJS course. Each exercise creates a real .xlsx file you can inspect in Excel.',code:"npm create vite@latest exceljs-lab -- --template react-ts\ncd exceljs-lab\nnpm install exceljs react-router-dom recharts\nnpm run dev",note:'ExcelJS creates workbooks; React supplies the learning interface and charts.'},
 {id:'install',title:'Install & configure',eyebrow:'Step 01',description:'Install ExcelJS, then import the workbook constructor into a focused export service. In Vite, browser downloads use writeBuffer(), not writeFile().',code:"import ExcelJS from 'exceljs'\n\nconst workbook = new ExcelJS.Workbook()\nconst sheet = workbook.addWorksheet('Report')\nconst buffer = await workbook.xlsx.writeBuffer()"},
 {id:'basics',title:'Workbook basics',eyebrow:'Step 02',description:'Create a workbook, a worksheet, named columns, data rows, and a formula. Download the example to see the result.',code:"sheet.columns = [\n  { header: 'Product', key: 'product', width: 24 },\n  { header: 'Revenue', key: 'revenue', width: 16 },\n]\nsheet.addRow({ product: 'Growth plan', revenue: 2400 })\nsheet.getCell('B4').value = { formula: 'SUM(B2:B3)' }",download:'basic'},
 {id:'styling',title:'Styles & formatting',eyebrow:'Step 03',description:'Make reports readable with font, fill, column widths, currency format, and frozen header rows.',code:"header.font = { bold: true, color: { argb: 'FFFFFFFF' } }\nheader.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: '0F766E' } }\nsheet.getCell('B3').numFmt = '$#,##0'\nsheet.views = [{ state: 'frozen', ySplit: 2 }]",download:'styled'},
 {id:'tables',title:'Advanced tables',eyebrow:'Step 04',description:'Excel tables add structured headers, filters, and row stripes. This lesson uses live mock API data when available.',code:"sheet.addTable({\n  name: 'UsersTable', ref: 'A1', headerRow: true,\n  style: { theme: 'TableStyleMedium2', showRowStripes: true },\n  columns: [{ name: 'Name' }, { name: 'Email' }],\n  rows: users.map(user => [user.name, user.email]),\n})",download:'table'},
 {id:'data',title:'Fetch mock data',eyebrow:'Step 05',description:'Fetch a public mock API, then show loading, error, and retry states before exporting. The reporting project contains the working example.',code:"const response = await fetch('https://jsonplaceholder.typicode.com/users')\nif (!response.ok) throw new Error('Could not load users')\nconst users = await response.json()"},
 {id:'downloads',title:'Download reports',eyebrow:'Step 06',description:'Create a Blob from the ExcelJS buffer and use a temporary link to download it. The project provides a link for every user.',code:"const buffer = await workbook.xlsx.writeBuffer()\nconst blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })\nconst link = document.createElement('a')\nlink.href = URL.createObjectURL(blob)\nlink.download = 'report.xlsx'\nlink.click()"},
 {id:'charts',title:'Charts & dashboard',eyebrow:'Step 07',description:'ExcelJS has robust table and workbook features, but native Excel chart creation is not part of its documented API. This app uses Recharts for live dashboard visualizations and exports a workbook with an embedded chart image and editable chart source data.',code:"<BarChart data={cityCounts}>\n  <XAxis dataKey=\"city\" />\n  <YAxis />\n  <Bar dataKey=\"users\" fill=\"#0f766e\" />\n</BarChart>",download:'chart',downloadLabel:'Download chart report .xlsx',examples:[{title:'Summarise mock data',description:'Group API users by city before sending the result to a chart or worksheet.',code:"const cityCounts = users.reduce((counts, user) => {\n  const city = user.address.city\n  counts[city] = (counts[city] ?? 0) + 1\n  return counts\n}, {})"},{title:'Draw a live dashboard chart',description:'Use Recharts for the interactive browser chart users see before downloading.',code:"<ResponsiveContainer width=\"100%\" height={280}>\n  <BarChart data={cityData}>\n    <Bar dataKey=\"users\" fill=\"#0f766e\" />\n  </BarChart>\n</ResponsiveContainer>"},{title:'Embed the chart in Excel',description:'Render a PNG in the browser, then add it to the Chart data worksheet with ExcelJS.',code:"const imageId = workbook.addImage({\n  base64: chartPng,\n  extension: 'png',\n})\nworksheet.addImage(imageId, {\n  tl: { col: 3, row: 1 },\n  ext: { width: 760, height: 360 },\n})"}]},
 {id:'complete',title:'Complete project',eyebrow:'Finish',description:'Put the pieces together in the Reporting project: fetch data, visualize it, and download individual or all-user reports.',code:"// Open the Reporting project from the menu.\n// Try individual downloads, then export the entire report.",note:'You now have a reusable browser reporting pattern.'}
]
