import ExcelJS from 'exceljs'
import type { User } from './types'

const teal = '0F766E'
const safe = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
function save(buffer: ExcelJS.Buffer, fileName: string) { const blob = new Blob([buffer as BlobPart], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = fileName; link.click(); URL.revokeObjectURL(link.href) }
function header(row: ExcelJS.Row) { row.font = { bold: true, color: { argb: 'FFFFFFFF' } }; row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: teal } }; row.alignment = { vertical: 'middle' } }
export async function basicWorkbook() { const book = new ExcelJS.Workbook(); const sheet = book.addWorksheet('Hello ExcelJS'); sheet.columns = [{ header: 'Product', key: 'product', width: 24 }, { header: 'Revenue', key: 'revenue', width: 16 }]; sheet.addRows([{product:'Starter plan', revenue:1200},{product:'Growth plan', revenue:2400}]); header(sheet.getRow(1)); sheet.getCell('B4').value = { formula: 'SUM(B2:B3)' }; sheet.getCell('A4').value = 'Total'; sheet.getRow(4).font = { bold: true }; save(await book.xlsx.writeBuffer(), '01-exceljs-basics.xlsx') }
export async function styledWorkbook() { const book = new ExcelJS.Workbook(); const sheet = book.addWorksheet('Styled report'); sheet.mergeCells('A1:D1'); sheet.getCell('A1').value = 'Monthly Revenue'; sheet.getCell('A1').font = { size: 18, bold: true, color: { argb: 'FFFFFFFF' } }; sheet.getCell('A1').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: teal } }; sheet.columns = [{width:16},{width:18},{width:18},{width:18}]; sheet.addRow(['Month','Revenue','Target','Status']); header(sheet.getRow(2)); [['January',12000,10000,'On track'],['February',9500,10000,'Watch'],['March',14300,10000,'On track']].forEach(row => sheet.addRow(row)); for(let i=3;i<=5;i++) { sheet.getCell(`B${i}`).numFmt = '$#,##0'; sheet.getCell(`C${i}`).numFmt = '$#,##0' }; sheet.views = [{ state:'frozen', ySplit:2 }]; save(await book.xlsx.writeBuffer(), '02-styled-report.xlsx') }
export async function tableWorkbook(users: User[]) { const book = new ExcelJS.Workbook(); const sheet = book.addWorksheet('User directory'); sheet.columns = [{width:24},{width:26},{width:18},{width:22}]; sheet.addTable({ name:'UsersTable', ref:'A1', headerRow:true, style:{theme:'TableStyleMedium2',showRowStripes:true}, columns:[{name:'Name'},{name:'Email'},{name:'City'},{name:'Company'}], rows: users.map(u => [u.name,u.email,u.address.city,u.company.name]) }); sheet.views = [{state:'frozen', ySplit:1}]; save(await book.xlsx.writeBuffer(), '03-advanced-excel-table.xlsx') }
export async function userWorkbook(user: User) { const book = new ExcelJS.Workbook(); const sheet = book.addWorksheet('User profile'); sheet.columns = [{width:20},{width:42}]; sheet.mergeCells('A1:B1'); sheet.getCell('A1').value = 'User Profile Report'; sheet.getCell('A1').font = {size:18,bold:true,color:{argb:'FFFFFFFF'}}; sheet.getCell('A1').fill = {type:'pattern',pattern:'solid',fgColor:{argb:teal}}; [['Name',user.name],['Username',user.username],['Email',user.email],['Phone',user.phone],['City',user.address.city],['Company',user.company.name],['Website',user.website]].forEach(row=>sheet.addRow(row)); for(let i=2;i<=8;i++) sheet.getCell(`A${i}`).font={bold:true}; save(await book.xlsx.writeBuffer(), `user-${String(user.id).padStart(2,'0')}-${safe(user.name)}.xlsx`) }
export async function allUsersWorkbook(users: User[]) { const book = new ExcelJS.Workbook(); const summary = book.addWorksheet('Summary'); summary.columns=[{width:28},{width:14}]; summary.addRows([['Users report',new Date()],['Total users',users.length],['Cities',new Set(users.map(u=>u.address.city)).size]]); summary.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}}; summary.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:teal}}; const data = book.addWorksheet('Users'); data.columns=[{width:24},{width:26},{width:18},{width:22},{width:20}]; data.addTable({name:'AllUsers',ref:'A1',headerRow:true,style:{theme:'TableStyleMedium2',showRowStripes:true},columns:[{name:'Name'},{name:'Email'},{name:'City'},{name:'Company'},{name:'Website'}],rows:users.map(u=>[u.name,u.email,u.address.city,u.company.name,u.website])}); data.views=[{state:'frozen',ySplit:1}]; save(await book.xlsx.writeBuffer(), 'complete-users-report.xlsx') }
